### ISSUE TITLE
.gitignore 파일에 .json 확장자 추가

### ISSUE THREAD

**Issue by ucyang** [minn951120/CCNCrawler#2]
크롤링 과정에서 생성된 JSON 파일들이 저장소에 커밋되고 있는데 아무래도 임시 데이터일 뿐이기에 커밋하지 않는 게 좋을 것 같습니다. 따라서 .gitignore 파일에 .json 확장자를 추가합시다.

**Comment by jm6534** [comment]
추가해서 커밋해주시면 감사합니다.

**Comment by jm6534** [comment]
해결돼서 이슈 닫겠습니다.
